language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t prashantjdrew/docker-react -f Dockerfile .
script:
  - docker run -e CI=true prashantjdrew/docker-react npm run test
